name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  strategy:
    matrix:
      alias:
      - :rama
      - :telemere

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: DeLaGuardo/setup-clojure@13.4
      with:
        cli: latest

    - uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
          .cpcache
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-

    - run: clojure -A${{ matrix.alias }} -X:rama
